# Generated by Django 4.2.6 on 2023-10-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_2',
            field=models.CharField(default=12, max_length=128),
            preserve_default=False,
        ),
    ]
