# Generated by Django 4.2.7 on 2023-11-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_ordercartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items_list',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='cart_items',
            field=models.ManyToManyField(blank=True, to='core.cartitem'),
        ),
    ]
