# Generated by Django 4.2.6 on 2023-10-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_password_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password_2',
            field=models.CharField(max_length=128, verbose_name='password_2'),
        ),
    ]
