# Generated by Django 4.2.6 on 2023-10-15 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='category',
            new_name='name',
        ),
    ]
