# Generated by Django 4.2.6 on 2023-10-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.ImageField(default=10, upload_to=''),
        ),
    ]
