# Generated by Django 4.2.6 on 2023-10-19 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_wishlistitem_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='quantity',
        ),
    ]
