# Generated by Django 4.2.6 on 2023-10-30 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_wishlistitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_in_wishlist',
            field=models.BooleanField(default=False),
        ),
    ]
