# Generated by Django 4.2.6 on 2023-10-30 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_cartitem_is_in_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='is_in_wishlist',
        ),
    ]
