# Generated by Django 4.2.7 on 2023-11-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_cartitem_options_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='overall',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
