# Generated by Django 4.2.7 on 2023-11-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_order_options_alter_wishlistitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('successful', 'Successful'), ('canceled', 'Canceled'), ('in_transit', 'In transit'), ('delivered', 'Delivered')], max_length=50),
        ),
    ]
