# Generated by Django 4.2.7 on 2023-11-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('successful', 'Successful'), ('canceled', 'Canceled'), ('in_transit', 'In transit'), ('delivered', 'Delivered')], default='Successful', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ManyToManyField(to='core.cartitem'),
        ),
    ]
